-- FlyNow Stage 1 PostgreSQL schema
-- Scope: the Google Sheet "Stage 1 Tracker", ending at READY_TO_DEPLOY.
-- This file defines the target schema only. It does not execute deployment,
-- Docker, Go worker, Traefik, queue, or runtime-container concerns.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- ---------------------------------------------------------------------------
-- Identity and access (sheet module 2; already represented in current code)
-- ---------------------------------------------------------------------------

CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(100) NOT NULL,
    username              VARCHAR(50) NOT NULL,
    email                 VARCHAR(254) NOT NULL,
    password              VARCHAR(100) NOT NULL,
    role                  VARCHAR(20) NOT NULL DEFAULT 'USER',
    status                VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    password_changed_at   TIMESTAMPTZ,
    last_login_at         TIMESTAMPTZ,
    failed_login_attempts INTEGER NOT NULL DEFAULT 0,
    locked_until          TIMESTAMPTZ,
    token_version         INTEGER NOT NULL DEFAULT 0,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_users_role
        CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_users_status
        CHECK (status IN ('ACTIVE', 'LOCKED', 'DISABLED')),
    CONSTRAINT ck_users_failed_login_attempts
        CHECK (failed_login_attempts >= 0),
    CONSTRAINT ck_users_token_version
        CHECK (token_version >= 0),
    CONSTRAINT ck_users_username_not_blank
        CHECK (btrim(username) <> ''),
    CONSTRAINT ck_users_email_not_blank
        CHECK (btrim(email) <> '')
);

-- Authentication treats usernames and emails as case-insensitive identifiers.
CREATE UNIQUE INDEX ux_users_username_lower ON users (lower(username));
CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE auth_sessions (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    family_id         UUID NOT NULL,
    user_id           BIGINT NOT NULL,
    token_hash        CHAR(64) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at        TIMESTAMPTZ NOT NULL,
    last_used_at      TIMESTAMPTZ,
    revoked_at        TIMESTAMPTZ,
    revocation_reason VARCHAR(100),
    replaced_by       UUID,
    user_agent        VARCHAR(500),
    ip_address        VARCHAR(64),

    CONSTRAINT fk_auth_sessions_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ux_auth_sessions_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_auth_sessions_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT ck_auth_sessions_revoked_at
        CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX ix_auth_sessions_user_active
    ON auth_sessions (user_id, expires_at)
    WHERE revoked_at IS NULL;
CREATE INDEX ix_auth_sessions_family ON auth_sessions (family_id);

CREATE TABLE auth_tokens (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    BIGINT NOT NULL,
    type       VARCHAR(30) NOT NULL,
    token_hash CHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at    TIMESTAMPTZ,

    CONSTRAINT fk_auth_tokens_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT ux_auth_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT ck_auth_tokens_type
        CHECK (type IN ('PASSWORD_RESET')),
    CONSTRAINT ck_auth_tokens_expiry
        CHECK (expires_at > created_at),
    CONSTRAINT ck_auth_tokens_used_at
        CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE INDEX ix_auth_tokens_user_type
    ON auth_tokens (user_id, type, expires_at)
    WHERE used_at IS NULL;

CREATE TABLE auth_audit_events (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT,
    event_type VARCHAR(60) NOT NULL,
    success    BOOLEAN NOT NULL,
    ip_address VARCHAR(64),
    user_agent VARCHAR(500),
    detail     VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_auth_audit_events_user
        FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
    CONSTRAINT ck_auth_audit_event_type_not_blank
        CHECK (btrim(event_type) <> '')
);

CREATE INDEX ix_auth_audit_events_user_created
    ON auth_audit_events (user_id, created_at DESC);
CREATE INDEX ix_auth_audit_events_type_created
    ON auth_audit_events (event_type, created_at DESC);

-- ---------------------------------------------------------------------------
-- Application management (sheet module 3)
-- ---------------------------------------------------------------------------

CREATE TABLE applications (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    owner_id        BIGINT NOT NULL,
    name            VARCHAR(100) NOT NULL,
    slug            VARCHAR(120) NOT NULL,
    description     VARCHAR(500),
    lifecycle_state VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMPTZ,

    CONSTRAINT fk_applications_owner
        FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT ck_applications_name_not_blank
        CHECK (btrim(name) <> ''),
    CONSTRAINT ck_applications_slug_format
        CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
    CONSTRAINT ck_applications_lifecycle_state
        CHECK (lifecycle_state IN ('DRAFT', 'CONFIGURING', 'READY_TO_DEPLOY')),
    CONSTRAINT ck_applications_deleted_at
        CHECK (deleted_at IS NULL OR deleted_at >= created_at)
);

-- A user may reuse a slug only after the old application is soft deleted.
CREATE UNIQUE INDEX ux_applications_owner_slug_active
    ON applications (owner_id, slug)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_applications_owner_updated
    ON applications (owner_id, updated_at DESC)
    WHERE deleted_at IS NULL;
CREATE INDEX ix_applications_owner_state
    ON applications (owner_id, lifecycle_state)
    WHERE deleted_at IS NULL;

CREATE TRIGGER trg_applications_updated_at
BEFORE UPDATE ON applications
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Source management and inspection (sheet modules 4 and 6)
-- One application has one active source configuration. Each upload, clone, or
-- webhook refresh creates an immutable source_versions row.
-- ---------------------------------------------------------------------------

CREATE TABLE application_sources (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id           UUID NOT NULL,
    source_type              VARCHAR(20) NOT NULL,
    repository_url           VARCHAR(2048),
    repository_full_name     VARCHAR(300),
    repository_branch        VARCHAR(255),
    webhook_secret_ciphertext BYTEA,
    webhook_secret_nonce      BYTEA,
    webhook_secret_key_version INTEGER,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_application_sources_application
        FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT ux_application_sources_application UNIQUE (application_id),
    CONSTRAINT ck_application_sources_type
        CHECK (source_type IN ('ZIP', 'GITHUB')),
    CONSTRAINT ck_application_sources_github_fields
        CHECK (
            (source_type = 'ZIP'
                AND repository_url IS NULL
                AND repository_full_name IS NULL
                AND repository_branch IS NULL)
            OR
            (source_type = 'GITHUB'
                AND repository_url IS NOT NULL
                AND repository_full_name IS NOT NULL
                AND repository_branch IS NOT NULL)
        ),
    CONSTRAINT ck_application_sources_webhook_secret
        CHECK (
            (webhook_secret_ciphertext IS NULL
                AND webhook_secret_nonce IS NULL
                AND webhook_secret_key_version IS NULL)
            OR
            (webhook_secret_ciphertext IS NOT NULL
                AND webhook_secret_nonce IS NOT NULL
                AND webhook_secret_key_version IS NOT NULL
                AND webhook_secret_key_version > 0)
        )
);

CREATE INDEX ix_application_sources_repository
    ON application_sources (lower(repository_full_name), repository_branch)
    WHERE source_type = 'GITHUB';

CREATE TRIGGER trg_application_sources_updated_at
BEFORE UPDATE ON application_sources
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE source_versions (
    id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    source_id                UUID NOT NULL,
    version_number           INTEGER NOT NULL,
    origin                   VARCHAR(20) NOT NULL,
    processing_status        VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    is_current               BOOLEAN NOT NULL DEFAULT FALSE,
    storage_key              VARCHAR(1024) NOT NULL,
    original_filename        VARCHAR(255),
    media_type               VARCHAR(150),
    size_bytes               BIGINT,
    checksum_sha256          CHAR(64),
    commit_sha               VARCHAR(64),
    file_tree                JSONB,
    detected_project_type    VARCHAR(30),
    detected_dockerfile_path VARCHAR(1024),
    failure_reason           VARCHAR(1000),
    created_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    inspected_at             TIMESTAMPTZ,

    CONSTRAINT fk_source_versions_source
        FOREIGN KEY (source_id) REFERENCES application_sources(id) ON DELETE CASCADE,
    CONSTRAINT ux_source_versions_number UNIQUE (source_id, version_number),
    CONSTRAINT ck_source_versions_number
        CHECK (version_number > 0),
    CONSTRAINT ck_source_versions_origin
        CHECK (origin IN ('ZIP_UPLOAD', 'GITHUB_CLONE', 'GITHUB_PUSH')),
    CONSTRAINT ck_source_versions_status
        CHECK (processing_status IN ('RECEIVED', 'STORED', 'EXTRACTED', 'INSPECTED', 'FAILED')),
    CONSTRAINT ck_source_versions_size
        CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CONSTRAINT ck_source_versions_checksum
        CHECK (checksum_sha256 IS NULL OR checksum_sha256 ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_source_versions_commit_sha
        CHECK (commit_sha IS NULL OR commit_sha ~ '^[0-9a-fA-F]{40,64}$'),
    CONSTRAINT ck_source_versions_file_tree
        CHECK (file_tree IS NULL OR jsonb_typeof(file_tree) IN ('array', 'object')),
    CONSTRAINT ck_source_versions_inspected_at
        CHECK (inspected_at IS NULL OR inspected_at >= created_at),
    CONSTRAINT ck_source_versions_failure_reason
        CHECK (
            (processing_status = 'FAILED' AND failure_reason IS NOT NULL)
            OR
            (processing_status <> 'FAILED' AND failure_reason IS NULL)
        )
);

-- Exactly zero or one version may be current for a source.
CREATE UNIQUE INDEX ux_source_versions_current
    ON source_versions (source_id)
    WHERE is_current;
CREATE INDEX ix_source_versions_source_created
    ON source_versions (source_id, created_at DESC);
CREATE INDEX ix_source_versions_commit_sha
    ON source_versions (commit_sha)
    WHERE commit_sha IS NOT NULL;

-- ---------------------------------------------------------------------------
-- GitHub webhook idempotency and processing audit (sheet module 5)
-- Full webhook payloads are deliberately not stored.
-- ---------------------------------------------------------------------------

CREATE TABLE github_webhook_deliveries (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    delivery_id          VARCHAR(100) NOT NULL,
    source_id            UUID,
    event_type           VARCHAR(100) NOT NULL,
    repository_full_name VARCHAR(300),
    branch               VARCHAR(255),
    commit_sha           VARCHAR(64),
    processing_status    VARCHAR(20) NOT NULL DEFAULT 'RECEIVED',
    ignored_reason       VARCHAR(500),
    error_detail         VARCHAR(1000),
    received_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at         TIMESTAMPTZ,

    CONSTRAINT fk_github_webhook_deliveries_source
        FOREIGN KEY (source_id) REFERENCES application_sources(id) ON DELETE SET NULL,
    CONSTRAINT ux_github_webhook_delivery_id UNIQUE (delivery_id),
    CONSTRAINT ck_github_webhook_status
        CHECK (processing_status IN ('RECEIVED', 'PROCESSED', 'IGNORED', 'FAILED')),
    CONSTRAINT ck_github_webhook_commit_sha
        CHECK (commit_sha IS NULL OR commit_sha ~ '^[0-9a-fA-F]{40,64}$'),
    CONSTRAINT ck_github_webhook_processed_at
        CHECK (processed_at IS NULL OR processed_at >= received_at),
    CONSTRAINT ck_github_webhook_ignored_reason
        CHECK (
            processing_status <> 'IGNORED'
            OR ignored_reason IS NOT NULL
        ),
    CONSTRAINT ck_github_webhook_error_detail
        CHECK (
            processing_status <> 'FAILED'
            OR error_detail IS NOT NULL
        )
);

CREATE INDEX ix_github_webhook_source_received
    ON github_webhook_deliveries (source_id, received_at DESC);
CREATE INDEX ix_github_webhook_status_received
    ON github_webhook_deliveries (processing_status, received_at);

-- ---------------------------------------------------------------------------
-- Desired server/runtime configuration only (sheet module 7).
-- Stage 1 stores this data but does not run containers.
-- ---------------------------------------------------------------------------

CREATE TABLE application_runtime_configs (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id        UUID NOT NULL,
    internal_port         INTEGER NOT NULL DEFAULT 8080,
    build_context_path    VARCHAR(1024) NOT NULL DEFAULT '.',
    dockerfile_path       VARCHAR(1024) NOT NULL DEFAULT 'Dockerfile',
    start_command         VARCHAR(1000),
    cpu_limit_millicores  INTEGER NOT NULL DEFAULT 500,
    memory_limit_mb       INTEGER NOT NULL DEFAULT 512,
    health_check_path     VARCHAR(1024),
    health_check_interval_seconds INTEGER NOT NULL DEFAULT 30,
    restart_policy        VARCHAR(20) NOT NULL DEFAULT 'ON_FAILURE',
    instance_count        INTEGER NOT NULL DEFAULT 1,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_application_runtime_configs_application
        FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT ux_application_runtime_configs_application UNIQUE (application_id),
    CONSTRAINT ck_runtime_internal_port
        CHECK (internal_port BETWEEN 1 AND 65535),
    CONSTRAINT ck_runtime_build_context_relative
        CHECK (
            build_context_path <> ''
            AND build_context_path !~ '^/'
            AND build_context_path !~ '(^|/)\.\.(/|$)'
        ),
    CONSTRAINT ck_runtime_dockerfile_relative
        CHECK (
            dockerfile_path <> ''
            AND dockerfile_path !~ '^/'
            AND dockerfile_path !~ '(^|/)\.\.(/|$)'
        ),
    CONSTRAINT ck_runtime_cpu_limit
        CHECK (cpu_limit_millicores BETWEEN 50 AND 64000),
    CONSTRAINT ck_runtime_memory_limit
        CHECK (memory_limit_mb BETWEEN 64 AND 1048576),
    CONSTRAINT ck_runtime_health_check_path
        CHECK (health_check_path IS NULL OR health_check_path ~ '^/'),
    CONSTRAINT ck_runtime_health_check_interval
        CHECK (health_check_interval_seconds BETWEEN 5 AND 3600),
    CONSTRAINT ck_runtime_restart_policy
        CHECK (restart_policy IN ('NO', 'ON_FAILURE', 'ALWAYS', 'UNLESS_STOPPED')),
    CONSTRAINT ck_runtime_instance_count
        CHECK (instance_count BETWEEN 1 AND 100)
);

CREATE TRIGGER trg_application_runtime_configs_updated_at
BEFORE UPDATE ON application_runtime_configs
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- Environment and secrets (sheet module 8)
-- All values are encrypted, including variables not marked secret. is_secret
-- controls API masking behavior; it does not weaken storage protection.
-- ---------------------------------------------------------------------------

CREATE TABLE application_environment_variables (
    id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id   UUID NOT NULL,
    name             VARCHAR(255) NOT NULL,
    value_ciphertext BYTEA NOT NULL,
    value_nonce      BYTEA NOT NULL,
    key_version      INTEGER NOT NULL,
    is_secret        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_application_environment_variables_application
        FOREIGN KEY (application_id) REFERENCES applications(id) ON DELETE CASCADE,
    CONSTRAINT ux_application_environment_variables_name
        UNIQUE (application_id, name),
    CONSTRAINT ck_environment_variable_name
        CHECK (name ~ '^[A-Za-z_][A-Za-z0-9_]*$'),
    CONSTRAINT ck_environment_variable_key_version
        CHECK (key_version > 0),
    CONSTRAINT ck_environment_variable_ciphertext
        CHECK (octet_length(value_ciphertext) > 0),
    CONSTRAINT ck_environment_variable_nonce
        CHECK (octet_length(value_nonce) = 12)
);

CREATE INDEX ix_environment_variables_application
    ON application_environment_variables (application_id, name);

CREATE TRIGGER trg_application_environment_variables_updated_at
BEFORE UPDATE ON application_environment_variables
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

COMMIT;

-- Readiness (sheet module 9) intentionally has no table. It is derived from:
-- applications.lifecycle_state
-- source_versions current INSPECTED record
-- source_versions.detected_dockerfile_path
-- application_runtime_configs
-- application_environment_variables
--
-- The readiness service returns its issue list and updates lifecycle_state to
-- READY_TO_DEPLOY only when all checks pass.
